baseURL = "https://www.artiltech.com/"
languageCode = "en-us"
theme = "chaklam"
publishDir = "docs"

title = "Artil Tech"

[params]
    logo = "/img/logo.png"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
  params = { section='#hero' }
[[menu.main]]
  name = 'Partners'
  pageRef = '/'
  weight = 20
  params = { section='#clients' }
[[menu.main]]
  name = 'Portfolio'
  pageRef = '/'
  weight = 30
  params = { section='#portfolio' }
[[menu.main]]
  name = 'Contact'
  pageRef = '/'
  weight = 40
  params = { section='#contact' }

[taxonomies]
  role = 'roles'

# https://gohugo.io/getting-started/configuration/